import = ["/home/hikaru/.config/alacritty/catppuccin-mocha.toml"]
#import = ["/home/hikaru/.config/alacritty/catppuccin-macchiato.toml"]
#import = ["/home/hikaru/.config/alacritty/catppuccin-frappe.toml"]
#import = ["/home/hikaru/.config/alacritty/catppuccin-latte.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 33

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 19

[window.padding]
x = 10
y = 10
